In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
dtype_cpc ={
    'patent_id': str,
    'cpc_sequence': int,
    'cpc_version_indicator': str,
    'cpc_section': 'category',
    'cpc_class': str,
    'cpc_subclass': str,
    'cpc_group': str,
    'cpc_type': 'category',
    'cpc_action_date': str
}

dtypes_ipc = {
    'patent_id': str,
    'ipc_sequence': int,
    'classification_level': 'category',
    #Create new column: section + "" + ipc_class + "" + subclass + "" + main_group + "/" + subgroup
    'section': 'category',
    'ipc_class': str,
    'subclass': str,
    'main_group': str,
    'subgroup': str,
    'classification_value': 'category',
    'classification_status': 'category',
    'classification_data_source': 'category',
    'action_date': str,
    'ipc_version_indicator': str
}

dtypes_location = {
    'rawlocation_id': str,
    'location_id': str,
    'raw_city': str,
    'raw_state': str,
    'raw_country': str
}

dtypes_inventor = {
    'patent_id': str,
    'inventor_sequence': int,
    'inventor_id': str,
    'raw_inventor_name_first': str,
    'raw_inventor_name_last': str,
    'deceased_flag': 'category',
    'rawlocation_id': str
}

In [3]:
df_cpc = pd.read_csv("g_cpc_at_issue.tsv", sep = "\t")
df_ipc = pd.read_csv("g_ipc_at_issue.tsv", sep = "\t", dtype = dtypes_ipc)
df_inventor = pd.read_csv("g_inventor_not_disambiguated.tsv", sep = "\t", dtype = dtypes_inventor)
df_location = pd.read_csv("g_location_not_disambiguated.tsv", sep = "\t", dtype = dtypes_location)

In [4]:
#could use del instead of drop 
df_cpc = df_cpc.drop(['cpc_sequence', 'cpc_section', 'cpc_class'], axis = 1)

df_ipc = df_ipc.drop(['ipc_sequence', 'classification_value', 'classification_status', 'classification_data_source'], axis=1)
df_ipc["ipc_group"] = df_ipc['section'].astype(str) + df_ipc['ipc_class'] + df_ipc['subclass'] + df_ipc['main_group'] + '/' + df_ipc['subgroup']
df_ipc = df_ipc.drop(['section', 'ipc_class', 'subclass', 'main_group', 'subgroup'], axis=1)

df_location = df_location.drop('location_id', axis=1)

df_inventor = df_inventor.drop(['inventor_sequence', 'inventor_id', 'raw_inventor_name_first', 'raw_inventor_name_last', 'deceased_flag'], axis=1)

In [5]:
df_cpc.head(30)

,patent_id,cpc_version_indicator,cpc_subclass,cpc_group,cpc_type,cpc_action_date
0,8992713,2013-01-01,H05K,H05K3/4644,additional,2015-03-31
1,9339050,2013-01-01,A23G,A23G3/0031,inventional,2016-05-17
2,10333523,2013-01-01,H01L,H01L43/08,inventional,2019-06-25
3,9562796,2013-01-01,G01F,G01F1/50,inventional,2017-02-07
4,9538186,2014-11-01,H04N,H04N19/172,inventional,2017-01-03
5,9630875,2013-01-01,C03C,C03C17/002,inventional,2017-04-25
6,9750728,2013-01-01,A61K,A61K31/436,inventional,2017-09-05
7,10700027,2013-01-01,H01L,H01L2924/1203,additional,2020-06-30
8,10605489,2018-05-01,F24S,F24S30/425,inventional,2020-03-31
9,10421211,2013-01-01,B27C,B27C1/02,inventional,2019-09-24
10,9406878,2013-01-01,H01L,H01L45/085,inventional,2016-08-02
11,9732779,2013-01-01,F16B,F16B5/065,inventional,2017-08-15
12,9822045,2013-01-01,F02K,F02K9/10,inventional,2017-11-21
13,9636695,2013-01-01,F04F,F04F5/14,inventional,2017-05-02
14,9029767,2013-01-01,H01J,H01J37/22,inventional,2015-05-12
15,8754020,2013-01-01,C10M,C10M2215/06,additional,2014-06-17
16,10285551,2013-01-01,A47L,A47L9/127,inventional,2019-05-14
17,10490459,2013-01-01,H01L,H01L29/1608,inventional,2019-11-26
18,10780666,2013-01-01,B29C,B29C66/3452,inventional,2020-09-22
19,10349164,2013-01-01,B01D,B01D2253/25,additional,2019-07-09
20,10179086,2013-01-01,A61H,A61H31/004,inventional,2019-01-15
21,10560717,2014-11-01,H04N,H04N19/521,inventional,2020-02-11
22,10540803,2013-01-01,G06T,G06T2219/2024,additional,2020-01-21
23,9672988,2013-01-01,H02J,H02J7/007,inventional,2017-06-06
24,9085074,2013-01-01,B23K,B23K37/00,inventional,2015-07-21
25,10775964,2013-01-01,G06F,G06F3/0482,inventional,2020-09-15
26,8989299,2013-01-01,H04L,H04L1/007,inventional,2015-03-24
27,9843685,2013-01-01,H04L,H04L41/22,inventional,2017-12-12
28,9114352,2013-01-01,B01D,B01D2257/504,additional,2015-08-25
29,9865482,2013-01-01,H01L,H01L2924/00014,additional,2018-01-09

In [6]:
df_ipc.head(30)

,patent_id,classification_level,action_date,ipc_version_indicator,ipc_group
0,10000000,A,2018-06-19,2006-01-01,G01S7/48
1,10000000,A,2018-06-19,2006-01-01,G01S7/486
2,10000000,A,2018-06-19,2006-01-01,G01S7/491
3,10000000,A,2018-06-19,2006-01-01,G01S13/89
4,10000001,A,2018-06-19,2006-01-01,B29C45/64
5,10000001,A,2018-06-19,2006-01-01,G05B19/18
6,10000001,A,2018-06-19,2006-01-01,B29C45/76
7,10000001,A,2018-06-19,2006-01-01,G05B19/402
8,10000001,A,2018-06-19,2006-01-01,B29C45/17
9,10000002,A,2018-06-19,2006-01-01,B32B7/0
10,10000002,A,2018-06-19,2006-01-01,B29C47/70
11,10000002,A,2018-06-19,2006-01-01,B32B27/8
12,10000002,A,2018-06-19,2006-01-01,B32B27/18
13,10000002,A,2018-06-19,2006-01-01,B60C5/14
14,10000002,A,2018-06-19,2006-01-01,B32B7/2
15,10000002,A,2018-06-19,2006-01-01,B32B27/0
16,10000002,A,2018-06-19,2006-01-01,B32B27/28
17,10000002,A,2018-06-19,2006-01-01,B32B27/34
18,10000002,A,2018-06-19,2006-01-01,B32B1/0
19,10000002,A,2018-06-19,2006-01-01,B32B3/0
20,10000002,A,2018-06-19,2006-01-01,B29C47/6
21,10000002,A,2018-06-19,2006-01-01,B29D30/6
22,10000002,A,2018-06-19,2006-01-01,B29C47/0
23,10000002,A,2018-06-19,2006-01-01,B29K21/0
24,10000002,A,2018-06-19,2006-01-01,B29K71/0
25,10000002,A,2018-06-19,2006-01-01,B29K77/0
26,10000002,A,2018-06-19,2006-01-01,B29L30/0
27,10000003,A,2018-06-19,2006-01-01,B65B7/0
28,10000003,A,2018-06-19,2006-01-01,B29C51/16
29,10000003,A,2018-06-19,2006-01-01,B29C47/0

In [7]:
df_location.head(30)

,rawlocation_id,raw_city,raw_state,raw_country
0,000005mtrirpdyrtlkfbffj0e,Kanagawa,NaN,JP
1,0000bztanu9rrtm943i8a7wry,Osaka,NaN,JP
2,0000c07c-672a-48d9-a3bb-71c439ac17b3,NaN,NaN,DE
3,0000dpr8zljw34um291yal5ym,Sugar Land,TX,US
4,0000dqyk4jrapg90sz5a4eog6,Austin,TX,US
5,0000g8ehwj0j8r2eubt3s0sso,Nundah,NaN,AU
6,0000iaytxly6w1a2q42efuk5p,Tokyo,NaN,JP
7,0000mzv8qbiyubouljdzswns2,Providence,RI,US
8,0000nl2head6ga63f9iwoa4w1,Lake Forest,CA,US
9,0000qgxbjrsk0mzjblu9rojeg,Villach,NaN,AT
10,0000s7h899s6oz4manm701nns,"Jhudong Township, Hsinchu County",NaN,TW
11,0000u1ntofpo3bnr6mv36z9gn,Issaquah,WA,US
12,0000vats1z1aoj64abhmc01fv,Ome,NaN,JP
13,0000w04iu6emmr1vnq8dproqk,Orange,CA,US
14,0000xio9ua92di2eyen90olhm,Bangalore,NaN,IN
15,00011fsq7xe2o4iuzjzqp19vt,Yokohama,NaN,JP
16,00011jsmg0v7iu4bh7hcuq6q6,Osaka,NaN,JP
17,00012bpxm3zw9ic3fntkt2y0n,Washington,DC,US
18,00013971kt4pntkrdox11u8hy,Graham,NC,US
19,00013da9-f242-4979-8cb1-72e4757cf1d5,NaN,NaN,GB
20,00017j0i6ulv93pyjuvxyxqfl,Nagano,NaN,JP
21,00019nwnj118o525j81d2ahpk,Tokyo,NaN,JP
22,0001d73e-5af0-424b-8ee1-bef880c45196,NaN,NaN,JP
23,0001e37jp4b9tc38djqqivinh,Susono,NaN,JPX
24,0001jr4pe4nf6judjbjf7ni7j,Carol Stream,IL,US
25,0001na2nwpyfreah6dl82nky3,Flemington,NJ,US
26,0001oq9jz0r0tbgse6qaf50et,Pensacola,FL,US
27,0001phowri2ble537ym7w7vbm,St. Petersburg,FL,US
28,0001pjj8tpsgixdh0w2vzkf6l,Bath,NaN,GB
29,0001q3nifjwyr5s50jw59s00t,Munich,NaN,DE

In [8]:
df_inventor.head(30)

   patent_id                        rawlocation_id
0    6584128             o2ema6bl3kkh6iwziprbzu4m9
1    4789863             tkz70bmoqx88n1lfz3fl657lh
2   11161990             up8ym622ssh09vpqv9rdsygs0
3    6795487             96s3xenagksk3dyad1r777a9e
4    D474886             cmf9hebugybql8ufffo47uwcz
5    7646155             omi6wqlrblholsssk9qx0dz5b
6    4339721             8uifwkdu885g2jxfu2uhnzgp1
7    6610738             hxh83mos96occibi6wg9fzfuy
8    6448562             cbejrj9ius2mty4ig27zqvj99
9    4432679             k7k03qpqzsoobzg1rgsr83q2e
10  11093663             1bxlrxn1xn78ktan0s40qovsi
11   8977851             ixb2b02fc6yq2q7fuj6hnycie
12  10761618             gh9hxrrfvxde1dnql02d8z3cw
13  10263820             5s6929sk5pwec66b95kvquzkw
14   6503081             m732umzzvzhty8sry4sljb0b0
15  10082632             l7ia29pnmnygzvsaxsmy9if7c
16   D935390             r8tqvihywohiq9kh7bzpecj16
17  10805689             msjom8m3fe4x410kz80nvfwyb
18   4513070             khvc4x5jvth76hbfdv89utj08
19  11585813             nxbahlwuq1ety98wlun0232nm
20   D294010             15gm5vzngg6l5v1kklnqej4yw
21   6705909             twmiifr71u9d7z6jbvgae1h6f
22   7423589             4e3xsynxi9e1ziqvin4skz8bf
23      H976  f1ce90e7-4ea9-4455-abdb-0ebb4aaf835f
24  10808661             crm9sz5p50lb9gvtfgqw2tljx
25   8873018             4zg0ygjf7c6j4ohta2irljnp3
26   5027236             65vvmqfywpkx9lfss99erie55
27   6060464             n2rw932sjbsek7c8lx9p67u7z
28   6495081             envk2alkmsx39oy0jf3xs1z9z
29  10025433             szo7d9mkxdzjjnfwypnc45le6

In [9]:
df_merge_cpc = pd.merge(df_cpc, df_inventor, on='patent_id', how='left')

In [10]:
df_merge_cpc = pd.merge(df_merge_cpc, df_location, on='rawlocation_id')

In [11]:
df_merge_ipc = pd.merge(df_ipc, df_inventor, on = 'patent_id', how='inner')

In [12]:
df_merge_ipc = pd.merge(df_merge_ipc, df_location, on='rawlocation_id')

In [13]:
df_inventor.info(memory_usage = "deep")
df_location.info(memory_usage = "deep")
df_cpc.info(memory_usage = "deep")
df_ipc.info(memory_usage = "deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21197038 entries, 0 to 21197037
Data columns (total 2 columns):
 #   Column          Dtype
---  ------          -----
 0   patent_id       object
 1   rawlocation_id  object
dtypes: object(2)
memory usage: 2.9 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34457017 entries, 0 to 34457016
Data columns (total 4 columns):
 #   Column          Dtype
---  ------          -----
 0   rawlocation_id  object
 1   raw_city        object
 2   raw_state       object
 3   raw_country     object
dtypes: object(4)
memory usage: 8.1 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058705 entries, 0 to 20058704
Data columns (total 6 columns):
 #   Column                 Dtype
---  ------                 -----
 0   patent_id              object
 1   cpc_version_indicator  object
 2   cpc_subclass           object
 3   cpc_group              object
 4   cpc_type               object
 5   cpc_action_date        object
dtypes: object(6)
memory usage: 7.4 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21846320 entries, 0 to 21846319
Data columns (total 5 columns):
 #   Column                 Dtype
---  ------                 -----
 0   patent_id              object
 1   classification_level   category
 2   action_date            object
 3   ipc_version_indicator  object
 4   ipc_group              object
dtypes: category(1), object(4)
memory usage: 5.1 GB

In [14]:
df_merge_cpc.head(30)

,patent_id,cpc_version_indicator,cpc_subclass,cpc_group,cpc_type,cpc_action_date,rawlocation_id,raw_city,raw_state,raw_country
0,8992713,2013-01-01,H05K,H05K3/4644,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
1,8992713,2013-01-01,B32B,B32B2038/0076,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
2,8992713,2013-01-01,B32B,B32B2309/02,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
3,8992713,2013-01-01,B32B,B32B2309/68,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
4,8992713,2013-01-01,B32B,B32B37/025,inventional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
5,8992713,2013-01-01,B32B,B32B2309/12,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
6,8992713,2013-01-01,B32B,B32B2309/105,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
7,8992713,2013-01-01,H05K,H05K2203/0228,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
8,8992713,2013-01-01,H05K,H05K3/4673,inventional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
9,8992713,2013-01-01,H05K,H05K2203/066,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
10,8992713,2013-01-01,B32B,B32B2311/00,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
11,8992713,2013-01-01,H05K,H05K2203/085,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
12,8992713,2013-01-01,B32B,B32B38/0004,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
13,8992713,2013-01-01,B32B,B32B2305/076,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
14,8992713,2013-01-01,B32B,B32B2457/08,additional,2015-03-31,frnu18lfj1vt16sxdtrr757by,Kawasaki,NaN,JP
15,8992713,2013-01-01,H05K,H05K3/4644,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
16,8992713,2013-01-01,B32B,B32B2038/0076,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
17,8992713,2013-01-01,B32B,B32B2309/02,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
18,8992713,2013-01-01,B32B,B32B2309/68,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
19,8992713,2013-01-01,B32B,B32B37/025,inventional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
20,8992713,2013-01-01,B32B,B32B2309/12,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
21,8992713,2013-01-01,B32B,B32B2309/105,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
22,8992713,2013-01-01,H05K,H05K2203/0228,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
23,8992713,2013-01-01,H05K,H05K3/4673,inventional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
24,8992713,2013-01-01,H05K,H05K2203/066,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
25,8992713,2013-01-01,B32B,B32B2311/00,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
26,8992713,2013-01-01,H05K,H05K2203/085,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
27,8992713,2013-01-01,B32B,B32B38/0004,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
28,8992713,2013-01-01,B32B,B32B2305/076,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP
29,8992713,2013-01-01,B32B,B32B2457/08,additional,2015-03-31,76k8xlyc5czpg4bm9mrw3tker,Kawasaki,NaN,JP

In [15]:
df_merge_ipc.head(30)

,patent_id,classification_level,action_date,ipc_version_indicator,ipc_group,rawlocation_id,raw_city,raw_state,raw_country
0,10000000,A,2018-06-19,2006-01-01,G01S7/48,klkuujc1w3iik6xrp7c2wdvt7,Manhattan Beach,CA,US
1,10000000,A,2018-06-19,2006-01-01,G01S7/486,klkuujc1w3iik6xrp7c2wdvt7,Manhattan Beach,CA,US
2,10000000,A,2018-06-19,2006-01-01,G01S7/491,klkuujc1w3iik6xrp7c2wdvt7,Manhattan Beach,CA,US
3,10000000,A,2018-06-19,2006-01-01,G01S13/89,klkuujc1w3iik6xrp7c2wdvt7,Manhattan Beach,CA,US
4,10000001,A,2018-06-19,2006-01-01,B29C45/64,zh7bez8b146hfu0buyxaa0v9b,Ansan-si,NaN,KR
5,10000001,A,2018-06-19,2006-01-01,G05B19/18,zh7bez8b146hfu0buyxaa0v9b,Ansan-si,NaN,KR
6,10000001,A,2018-06-19,2006-01-01,B29C45/76,zh7bez8b146hfu0buyxaa0v9b,Ansan-si,NaN,KR
7,10000001,A,2018-06-19,2006-01-01,G05B19/402,zh7bez8b146hfu0buyxaa0v9b,Ansan-si,NaN,KR
8,10000001,A,2018-06-19,2006-01-01,B29C45/17,zh7bez8b146hfu0buyxaa0v9b,Ansan-si,NaN,KR
9,10000001,A,2018-06-19,2006-01-01,B29C45/64,95igh4mbo217kt9dmb2x8r3il,Gunpo-si,NaN,KR
10,10000001,A,2018-06-19,2006-01-01,G05B19/18,95igh4mbo217kt9dmb2x8r3il,Gunpo-si,NaN,KR
11,10000001,A,2018-06-19,2006-01-01,B29C45/76,95igh4mbo217kt9dmb2x8r3il,Gunpo-si,NaN,KR
12,10000001,A,2018-06-19,2006-01-01,G05B19/402,95igh4mbo217kt9dmb2x8r3il,Gunpo-si,NaN,KR
13,10000001,A,2018-06-19,2006-01-01,B29C45/17,95igh4mbo217kt9dmb2x8r3il,Gunpo-si,NaN,KR
14,10000002,A,2018-06-19,2006-01-01,B32B7/0,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
15,10000002,A,2018-06-19,2006-01-01,B29C47/70,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
16,10000002,A,2018-06-19,2006-01-01,B32B27/8,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
17,10000002,A,2018-06-19,2006-01-01,B32B27/18,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
18,10000002,A,2018-06-19,2006-01-01,B60C5/14,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
19,10000002,A,2018-06-19,2006-01-01,B32B7/2,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
20,10000002,A,2018-06-19,2006-01-01,B32B27/0,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
21,10000002,A,2018-06-19,2006-01-01,B32B27/28,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
22,10000002,A,2018-06-19,2006-01-01,B32B27/34,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
23,10000002,A,2018-06-19,2006-01-01,B32B1/0,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
24,10000002,A,2018-06-19,2006-01-01,B32B3/0,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
25,10000002,A,2018-06-19,2006-01-01,B29C47/6,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
26,10000002,A,2018-06-19,2006-01-01,B29D30/6,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
27,10000002,A,2018-06-19,2006-01-01,B29C47/0,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
28,10000002,A,2018-06-19,2006-01-01,B29K21/0,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR
29,10000002,A,2018-06-19,2006-01-01,B29K71/0,zydhvwsuwge17kk1w8gla8c01,Yongin-si,NaN,KR

In [16]:
df_merge_ipc.info(memory_usage = "deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62007094 entries, 0 to 62007093
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   patent_id              object
 1   classification_level   category
 2   action_date            object
 3   ipc_version_indicator  object
 4   ipc_group              object
 5   rawlocation_id         object
 6   raw_city               object
 7   raw_state              object
 8   raw_country            object
dtypes: category(1), object(8)
memory usage: 29.2 GB

In [17]:
df_merge_cpc.info(memory_usage = "deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62132214 entries, 0 to 62132213
Data columns (total 10 columns):
 #   Column                 Dtype
---  ------                 -----
 0   patent_id              object
 1   cpc_version_indicator  object
 2   cpc_subclass           object
 3   cpc_group              object
 4   cpc_type               object
 5   cpc_action_date        object
 6   rawlocation_id         object
 7   raw_city               object
 8   raw_state              object
 9   raw_country            object
dtypes: object(10)
memory usage: 37.4 GB

In [ ]:
# df_merge_cpc.to_csv('merge_cpc.csv', index=False)
# df_merge_ipc.to_csv('merge_ipc.csv', index=False)
# Chạy 2 câu lệnh này để lưu file